# Generated by Django 4.2.5 on 2023-09-14 22:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AltKategoriler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MasalKategoriAdi", models.CharField(max_length=30, unique=True)),
                (
                    "MasalSlug",
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
                ("HikayeKategoriAdi", models.CharField(blank=True, max_length=255)),
                ("HikayeSlug", models.SlugField(blank=True, max_length=255)),
                ("EnglishKategoriAdi", models.CharField(blank=True, max_length=255)),
                ("EnglishSlug", models.SlugField(blank=True, max_length=255)),
                (
                    "kapak_resmi",
                    models.ImageField(
                        help_text="Anasayfa Resim", upload_to="kapak_resimleri/"
                    ),
                ),
                (
                    "Masal_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "Masal_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                (
                    "Hikaye_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                        verbose_name="Meta Açıklama Söz",
                    ),
                ),
                (
                    "Hikaye_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                        verbose_name="Anahtar Kelimeler Söz",
                    ),
                ),
                (
                    "English_Hikaye_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                        verbose_name="Meta Açıklama Söz",
                    ),
                ),
                (
                    "English_Hikaye_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                        verbose_name="Anahtar Kelimeler Söz",
                    ),
                ),
                ("Masal", models.BooleanField(default=False)),
                ("Hikaye", models.BooleanField(default=False)),
                ("English", models.BooleanField(default=False)),
                ("aktif", models.BooleanField(default=True)),
                ("banner", models.BooleanField(default=False)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Tüm Alt Kategoriler",},
        ),
        migrations.CreateModel(
            name="SiirMasal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Şiirin başlığını girin.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Şiirin URL'de görünecek kısmını girin.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "Model",
                    models.CharField(
                        choices=[
                            ("Hikaye", "Hikaye"),
                            ("Masal", "Masal"),
                            ("ingilizcehikaye", "ingilizcehikaye"),
                        ],
                        help_text="Modele göre sılanma ve konumlandırılma olacaktır.",
                        max_length=40,
                    ),
                ),
                (
                    "icerik",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Şiirin içeriğini girin.", null=True
                    ),
                ),
                ("youtube", models.TextField(blank=True, null=True)),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Taslak", "Taslak"),
                            ("Hazir", "Hazir"),
                            ("Yayinda", "Yayinda"),
                            ("Kontrol", "Kontrol"),
                            ("Reddedildi", "Reddedildi"),
                        ],
                        default="Taslak",
                        help_text="Şiirin durumunu seçin.",
                        max_length=10,
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=False,
                        help_text="Şiirin aktif olup olmadığını belirtin.",
                    ),
                ),
                (
                    "banner",
                    models.BooleanField(
                        default=False,
                        help_text="Ana Sayfadaki büyük resim alanında ögrünür",
                    ),
                ),
                (
                    "small_banner",
                    models.BooleanField(
                        default=False, help_text="Ana sayfada küçük resimlerde görünür."
                    ),
                ),
                ("okunma_sayisi", models.PositiveBigIntegerField(default=0)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "alt_kategorisi",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Şiirin alt kategorilerini seçin.",
                        to="Hepsi.altkategoriler",
                    ),
                ),
            ],
        ),
    ]
