# Generated by Django 4.2.5 on 2023-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="altkategoriler", name="kapak_resmi",),
        migrations.AddField(
            model_name="altkategoriler",
            name="kapak_resmi_Hikayeler",
            field=models.ImageField(
                blank=True, help_text="Anasayfa Resim", upload_to="kapak_resimleri/"
            ),
        ),
        migrations.AddField(
            model_name="altkategoriler",
            name="kapak_resmi_Hikayeler_English",
            field=models.ImageField(
                blank=True, help_text="Anasayfa Resim", upload_to="kapak_resimleri/"
            ),
        ),
        migrations.AddField(
            model_name="altkategoriler",
            name="kapak_resmi_Masallar",
            field=models.ImageField(
                blank=True, help_text="Anasayfa Resim", upload_to="kapak_resimleri/"
            ),
        ),
        migrations.AlterField(
            model_name="altkategoriler",
            name="English_Hikaye_keywords",
            field=models.CharField(
                blank=True,
                help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="altkategoriler",
            name="English_Hikaye_meta_description",
            field=models.TextField(
                blank=True, help_text="Sayfanın meta açıklamasını girin.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="altkategoriler",
            name="Hikaye_keywords",
            field=models.CharField(
                blank=True,
                help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="altkategoriler",
            name="Hikaye_meta_description",
            field=models.TextField(
                blank=True, help_text="Sayfanın meta açıklamasını girin.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="altkategoriler",
            name="Masal_keywords",
            field=models.CharField(
                blank=True,
                help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="altkategoriler",
            name="Masal_meta_description",
            field=models.TextField(
                blank=True, help_text="Sayfanın meta açıklamasını girin."
            ),
        ),
    ]
