# Generated by Django 4.2.5 on 2023-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0002_remove_altkategoriler_kapak_resmi_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="altkategoriler", name="banner",),
        migrations.AddField(
            model_name="altkategoriler",
            name="bannerHikaye",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="altkategoriler",
            name="bannerHikayeEnglish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="altkategoriler",
            name="bannerMasal",
            field=models.BooleanField(default=False),
        ),
    ]
