# Generated by Django 4.2.5 on 2023-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0003_remove_altkategoriler_banner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HikayeKategorileri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HikayeKategoriAdi", models.CharField(blank=True, max_length=255)),
                ("HikayeSlug", models.SlugField(blank=True, max_length=255)),
                (
                    "Hikaye_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                    ),
                ),
                (
                    "Hikaye_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "kapak_resmi_Hikayeler",
                    models.ImageField(
                        blank=True,
                        help_text="Anasayfa Resim",
                        upload_to="kapak_resimleri/",
                    ),
                ),
                ("Aktif", models.BooleanField(default=False)),
                ("Banner", models.BooleanField(default=False)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Hikayeler",},
        ),
        migrations.CreateModel(
            name="MasalKategorileri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MasalKategoriAdi", models.CharField(max_length=30, unique=True)),
                (
                    "MasalSlug",
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
                (
                    "Masal_meta_description",
                    models.TextField(
                        blank=True, help_text="Sayfanın meta açıklamasını girin."
                    ),
                ),
                (
                    "Masal_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                    ),
                ),
                (
                    "kapak_resmi_Masallar",
                    models.ImageField(
                        blank=True,
                        help_text="Anasayfa Resim",
                        upload_to="kapak_resimleri/",
                    ),
                ),
                ("Aktif", models.BooleanField(default=False)),
                ("Banner", models.BooleanField(default=False)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Masallar",},
        ),
        migrations.RemoveField(model_name="siirmasal", name="alt_kategorisi",),
        migrations.AlterField(
            model_name="siirmasal",
            name="Model",
            field=models.CharField(
                choices=[("Hikaye", "Hikaye"), ("Masal", "Masal")],
                help_text="Modele göre sılanma ve konumlandırılma olacaktır.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="siirmasal",
            name="status",
            field=models.CharField(
                choices=[
                    ("Taslak", "Taslak"),
                    ("Hazir", "Hazir"),
                    ("Yayinda", "Yayinda"),
                ],
                default="Taslak",
                help_text="Şiirin durumunu seçin.",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(name="AltKategoriler",),
        migrations.AddField(
            model_name="siirmasal",
            name="hikayeKategorisi",
            field=models.ManyToManyField(
                blank=True,
                help_text="Şiirin alt kategorilerini seçin.",
                to="Hepsi.hikayekategorileri",
            ),
        ),
        migrations.AddField(
            model_name="siirmasal",
            name="masakKategorisi",
            field=models.ManyToManyField(
                blank=True,
                help_text="Şiirin alt kategorilerini seçin.",
                to="Hepsi.masalkategorileri",
            ),
        ),
    ]
