# Generated by Django 4.2.5 on 2023-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0004_hikayekategorileri_masalkategorileri_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hikayekategorileri", name="kapak_resmi_Hikayeler",
        ),
        migrations.RemoveField(
            model_name="masalkategorileri", name="kapak_resmi_Masallar",
        ),
        migrations.AddField(
            model_name="hikayekategorileri",
            name="resimyolu",
            field=models.CharField(blank=True, max_length=88),
        ),
        migrations.AddField(
            model_name="masalkategorileri",
            name="resimyolu",
            field=models.CharField(blank=True, max_length=88),
        ),
    ]
