# Generated by Django 4.2.5 on 2023-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0005_remove_hikayekategorileri_kapak_resmi_hikayeler_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hikayekategorileri",
            name="resimyolu",
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name="masalkategorileri",
            name="resimyolu",
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
    ]
