# Generated by Django 4.2.5 on 2023-09-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0008_hikayekategorileri_sirasi_masalkategorileri_sirasi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hikayekategorileri",
            options={"verbose_name_plural": "Hikayeler Kategorileri"},
        ),
        migrations.AlterModelOptions(
            name="masalkategorileri",
            options={"verbose_name_plural": "Masallar Kategorileri"},
        ),
        migrations.AlterModelOptions(
            name="siirmasal", options={"verbose_name_plural": "Post"},
        ),
        migrations.RenameField(
            model_name="siirmasal",
            old_name="masakKategorisi",
            new_name="masalKategorisi",
        ),
    ]
