# Generated by Django 4.2.5 on 2023-09-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0009_alter_hikayekategorileri_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="siirmasal", name="youtube",),
    ]
