# Generated by Django 4.2.5 on 2023-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hepsi", "0010_remove_siirmasal_youtube"),
    ]

    operations = [
        migrations.AddField(
            model_name="siirmasal", name="youtube", field=models.URLField(blank=True),
        ),
    ]
